# Site settings
title: Angelica Li | Portfolio
description: My personal portfolio website.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# url: "http://angelicali.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Angelica Li
user_description: I'm a recent graduate from the CS Specialist program at the University of Toronto with a focus in Artificial Intelligence. I'm passionate about applications in machine learning, computer vision, and natural language processing and have experience as a full stack software developer. I'm originally from Lima, Peru and some hobbies I have are painting and reading about astronomy and astrophysics.
user_title: Software Developer
email: liley.angelica@gmail.com
github_username:  angelicali93

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
